language: python
dist: focal
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
addons:
  apt:
    packages:
    - scons
cache:
  pip: true
  directories:
    - $HOME/perl5
install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libtest-exception-perl libtest-output-perl libdevel-cover-perl acl cpanminus libcgi-pm-perl
  - pip install codecov flask pytest-cov pytest-pep8
  - sudo cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Codecov
script:
  - scons python=$(which python) test
  - py.test --cov=account/account --cov-branch --pep8 account
after_success:
  - coverage combine
  - codecov
  - cd test/frontend && cover -report codecov
