language: python
python:
  - 2.6
  - 2.7
install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libtest-exception-perl libtest-output-perl libdevel-cover-perl acl cpanminus
  - pip install codecov
  - sudo cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Codecov
script:
  - scons python=$(which python) test
after_success:
  - coverage combine && codecov
  - cd test/frontend && cover -report codecov
