import os

Import('env')

ws_script = 'web_service.py'
python_files = [ '__init__.py', 'make_web_service.py', ws_script ]

# Install .py files:
instdir = os.path.join(env['pythondir'], 'saliweb')
pyinst = env.Install(instdir, python_files)
env.Alias('install', pyinst)

# Also install web_service.py in the path
cmdinst = env.Install(env['bindir'], ws_script)
env.Alias('install', cmdinst)

SConscript('backend/SConscript')
SConscript('build/SConscript')
SConscript('test/SConscript')
