import os

Import('env')

python_files = [ '__init__.py', 'make_web_service.py', 'web_service.py' ]

# Install .py files:
instdir = os.path.join(env['pythondir'], 'saliweb')
pyinst = env.Install(instdir, python_files)
env.Alias('install', pyinst)

SConscript('backend/SConscript')
SConscript('build/SConscript')
SConscript('test/SConscript')
