import os

Import('env')

python_files = [ '__init__.py', 'run-tests.py' ]

# Install .py files:
instdir = os.path.join(env['pythondir'], 'saliweb', 'test')
pyinst = env.Install(instdir, python_files)
env.Alias('install', pyinst)

SConscript('MySQLdb/SConscript')
