import os.path

Import('env')

# Set http_proxy for Sphinx if necessary
if env.get('http_proxy', None):
    env['ENV']['http_proxy'] = env['http_proxy']
if env.get('https_proxy', None):
    env['ENV']['https_proxy'] = env['https_proxy']

sphinx = env.Sphinx(".build/html/index.html",
                    (Glob('*.rst'), Glob('modules/*.rst'),
                     Glob('#/examples/*'),
                     Glob('#/python/saliweb/*/*.py')))

docdir = env['docdir']
env.SphinxInstall(os.path.join(docdir, 'index.html'), sphinx)
env.Alias('docinstall', docdir)
