import os

Import('env')

templates = ['layout.html', 'queue.html', 'user_error.html',
             'results_error.html', 'help.xml', 'results.xml',
             'results_error.xml', 'user_error.xml', 'submit.xml',
             'internal_error.html', 'internal_error.xml',
             'access_denied_error.html', 'access_denied_error.xml']

# Install template files:
instdir = os.path.join(env['pythondir'], 'saliweb', 'frontend', 'templates',
                       'saliweb')
tmplinst = env.Install(instdir, templates)
env.Alias('install', tmplinst)
