import os

Import('env')

python_files = [ '__init__.py', 'cursors.py' ]

# Install .py files:
instdir = os.path.join(env['pythondir'], 'saliweb', 'test', 'MySQLdb')
pyinst = env.Install(instdir, python_files)
env.Alias('install', pyinst)
