import os

Import('env')

e = env.Clone()

# Custom builder to run unit tests:
def builder_unit_test(target, source, env):
    dir = os.path.dirname(str(source[0]))
    app = "cd %s && prove -v *.pl" % dir
    if e.Execute(app) == 0:
        file(str(target[0]), 'w').write('PASSED\n')
    else:
        print "unit tests FAILED"
        return 1
e.Append(BUILDERS = {'Test': Builder(action=builder_unit_test)})

test = e.Test("test.passed", 'SConscript')
# Always run our unit tests:
e.AlwaysBuild("test.passed")
Return('test')
