import os

Import('env')

python_files = [ '__init__.py', 'service.py', 'resubmit.py', 'deljob.py',
                 'events.py', 'sge.py', 'failjob.py', 'delete_all_jobs.py' ]

# Install .py files:
instdir = os.path.join(env['pythondir'], 'saliweb', 'backend')
pyinst = env.Install(instdir, python_files)
env.Alias('install', pyinst)
