import os

Import('env')

python_files = [ '__init__.py', 'process_jobs.py', 'resubmit.py' ]

# Install .py files:
instdir = os.path.join(env['pythondir'], 'saliweb', 'backend')
pyinst = env.Install(instdir, python_files)
env.Alias('install', pyinst)
