name: build

on: [push, pull_request]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        python-version: [3.6, 3.7, 3.8, 3.9]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get -qq update && sudo apt-get install -y libtest-exception-perl libtest-output-perl libdevel-cover-perl acl cpanminus libcgi-pm-perl perl-doc
        pip install codecov flask pytest-cov pytest-flake8 coverage scons
        sudo cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Codecov
        # Patch Devel::Cover::Report::Codecov to support GitHub Actions
        # from https://github.com/codecov/codecov-perl/pull/41
        reportdir=$(dirname $(perldoc -l Devel::Cover::Report::Codecov) )
        curl https://github.com/codecov/codecov-perl/commit/75ac8c01b3cccbff0acc879467b3952cd9605210.patch > gha.patch && patch -p5 < gha.patch && sudo cp Codecov/Service/GitHub.pm $reportdir/Codecov/Service/GitHub.pm
    - name: Test
      run: |
        scons python=$(which python) test
        py.test --cov=account/account --cov-branch --flake8 account
    - name: Upload coverage to codecov
      run: |
        bash <(curl -s https://codecov.io/bash)
        cd test/frontend && cover -report codecov
