import os

Import('env')

perl_files = [ 'frontend.pm', 'server.pm' ]

# Install files:
instdir = os.path.join(env['perldir'], 'saliweb')
plinst = env.Install(instdir, perl_files)
env.Alias('install', plinst)
